### ISSUE TITLE
Trying to create contact and account at the same time

### ISSUE THREAD

**Issue by scrazzymoto** [Saleslogix/DotNetSDataClient#12]
Trying to do something like this:

```
var contact = new Contact { Email = "jschmoe@cmp123.com",
                                               FirstName = "Joe",
                                               LastName = "Schmoe", 
                                               Account = new Account { AccountName = "Company 123", 
                                                                                         Type = "End Users", 
                                                                                         Status = "Active" 
                                                                                        } 
                                              };

var options = new SDataPayloadOptions { Include = "Accounts" };
var results = _client.PostAsync(contact, null, options).Result;
```

However, when I run this code, the server returns this error:

_object references an unsaved transient instance - save the transient instance before flushing or set cascade action for the property to something that would make it autosave._

**Comment by NathanBaulch** [comment]
This is a server-side limitation, not a client issue. In general, it's better to create parent-child entities from the parent's perspective. In other words, create the account with a nested contact.

The following works for me:
```csharp
var account = new Account
    {
        AccountName = "Company 123",
        Type = "End Users",
        Status = "Active",
        Contacts = new List<Contact>
            {
                new Contact
                    {
                        Email = "jschmoe@cmp123.com",
                        FirstName = "Joe",
                        LastName = "Schmoe"
                    }
            }
    };
var options = new SDataPayloadOptions {Include = "Contacts"};
var results = client.PostAsync(account, null, options).Result;
```

**Comment by scrazzymoto** [comment]
Awesome, thank you!

**Comment by joeshmoe301** [comment]
I have been trying to follow the examples [on this page](https://github.com/Saleslogix/DotNetSDataClient/wiki/Resources).  Reading data works, but when I try to create a contact by itself, I receive the error "The Contact's Account is required."  I found this issue and then tried your code to create the account and contact at the same time.  I now receive the error "The remote server returned an error: (404) Not Found." (see attached image).
![dotnetsdataclient-error](https://cloud.githubusercontent.com/assets/770537/20403703/dc33fdb0-accf-11e6-93e7-0cdda06acc42.jpg)

Any ideas what I am doing wrong?  

Does any other documentation exist?  For example, where does your Account class code exist?  I just assumed what it should be and used this: `
    [SDataPath("account")]
    public class Account
    {
        [SDataProtocolProperty(SDataProtocolProperty.Key)]
        public string Id { get; set; }

        public string AccountName { get; set; }
        public List<Contact> Contacts { get; set; }
        public string Status { get; set; }
        public string Type { get; set; }
    }`

Thanks

**Comment by RyanFarley** [comment]
@joeshmoe301 For your Account class, the SDataPath should be "accounts" (plural), not "account".

**Comment by joeshmoe301** [comment]
Thanks.  I added the 's' and got it to work.  Is there any documentation for this that I missed?  I'm assuming that I should have known to use "accounts" based on [this link](http://developer.saleslogix.com/DotNetSDataClient/whitepaper/dynamic_endpoints.html) in the "Sample Calls" section, but is there any other code examples using DotNetSDataClient.

**Comment by RyanFarley** [comment]
Not sure if there is any documentation for that specifically (I don't believe so). However, for any entity, you can see what it's SData path is by opening the entity in AA and looking at the SData tab. It will show what it's SData path is there in the Path Name field.

**Comment by joeshmoe301** [comment]
Thanks again for the help.

**Comment by joeshmoe301** [comment]
How can you add a contact and associate it with an already existing account?  I tried the below code, but I keep getting an error (just a generic 500 error).

`var client = new SDataClient("https://domain/sdata/slx/dynamic/-/")
    {
        UserName = "username",
        Password = "password"
    };

    var contact = new Contact
    {
        Account = new Account
        {
            AccountName = "accountName",
            Id = "accountId"
        },
        Address = new Address
        {
            Address1 = "1234 Address",
            City = "someCity",
            PostalCode = "12345",
            State = "ST"
        },
        FirstName = "John",
        LastName = "Doe"
    };

    var contactOptions = new SDataPayloadOptions { Include = "Address" };

    try
    {
        contact = client.Post(contact, null, contactOptions);
    }
    catch (Exception ex)
    {
        var error = ex.Message;
    }`

**Comment by RyanFarley** [comment]
@joeshmoe301 

The issue is that your POCO for Account has a collection of contacts. The DotNetSDataClient is serializing that as null and the SData server doesn't like that. Even setting that collection to new List<Contact>() will fail because it will get serialized as []. where it should look like 
```
"Contacts": { "$resources": [] }
```

A work around is to add this attribute to your Contacts collection in the Account POCO:

```
[SDataProtocolProperty(SDataProtocolProperty.DeleteMissing)]
public List<Contact> Contacts { get; set; }
```

You'll likely have to add that attribute to your AccountName property as well, otherwise you'll get a 500 back for that being empty. However, once adding that, it should work fine.


@NathanBaulch would it be possible for it to serialize Empty collections as either { "$resources": [] } or just default to Delete them since an empty array doesn't need to be included anyway? I can't think of any reason for empty arrays to be included in the serialized JSON.

**Comment by RyanFarley** [comment]
_(Deleted my previous response about using the DeleteMissing attribute. I think I was thinking of another library since in SData there's a $deleteMissing attribute for SData Sync that has other meanings)_

There might be other ways, but sometimes when I am using POCOs I create an entity with just an Id property like this:

```
public class EntityResource
{
	[SDataProtocolProperty(SDataProtocolProperty.Key)]
	public string Id { get; set; }
}
```

and then I use that for updates for existing parent entities (in place of something like Account). That works great for associating data with existing entities, but doesn't work well for using the same entity for creating new records since you don't have the other properties.

**Comment by RyanFarley** [comment]
The real issue here is that the POCO for Account has a collection of contacts. The DotNetSDataClient is serializing that as null and the SData server doesn't like that. Even setting that collection to new List() will fail because it will get serialized as []. where it should look like

```
"Contacts": { "$resources": [] }
```

When doing a POST with an existing parent or related entity, SData expects to only receive the $key and nothing else anyway. So, when the Contact class gets serialized, what you should be sending with the contact data is

```
"Account": { "$key":"AXXX00000001" }
```

and nothing more, but that is not the case, the library is serializing and sending everything. 

@NathanBaulch ideally, when sending a POST, if a nested entity already contains a $key, it should strip out all else and leave just the $key. Is there a way to do this?

**Comment by joeshmoe301** [comment]
Thank you for the response.  I was able to get this to work using your suggestion for creating an account class with only the key.

Trying to figure out how to use this library has been difficult for me.  Is there any way I could have known how to implement this work around without someone else sharing this with me?  I have access to the schema (https://domain/sdata/slx/dynamic/-/$schema), but this doesn't seem to provide everything that I need (or maybe I just don't know how to read the schema well enough).  What is your opinion?  Do you have any suggestions on how to learn to use this library better?

Thank you again for your response.

**Comment by NathanBaulch** [comment]
There's no easy solution for this problem right now I'm afraid. I'll have to think a bit more about how we should handle parent references when inserting new entities via a typed model.

For now the workaround is to create a base class that only has the $key property as suggested and use that type for reference properties instead.

```csharp
public class Contact
{
    public AccountBase Account { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }
}

public class AccountBase
{
    [SDataProtocolProperty]
    public string Key { get; set; }
}

[SDataPath("accounts")]
public class Account : AccountBase
{
    public string AccountName { get; set; }
    public string Type { get; set; }
    public string Status { get; set; }
}
```

**Comment by RyanFarley** [comment]
@NathanBaulch I do it that way as well. The downside is that you can't use the same entity for reads since the feeds are deserialized as AccountBase instead of Account so you only end up with the ID only. This means the only way you can use POCOs and have it all work is to have a different set of POCOs for reads, which you can also use for creating all new data, and another set for creating new data for existing relationships.

Ideally, the SData server would see the nested entity has a $key and would ignore everything else, knowing that it references an existing entity. Either way, the thing that causes the issue is when your POCO has a nested List of entities, like List<Contact> and the value is null. If the value would be set as "Contacts": { "$resources": [] } instead then the SData server doesn't fail on the request. I've tried initializing my lists to new List<Contact>() but that doesn't solve it since it gets serialized to just "Contacts": [] instead of "Contacts": { "$resources": [] }. Is there a way to force an empty list to serialize to "Contacts": { "$resources": [] } rather than "Contacts": [] ?

**Comment by NathanBaulch** [comment]
Thanks @RyanFarley, both issues have been fixed in version 2.0.1.1560. Empty resource collections are now serialized correctly and resources with `$key` specified have their properties excluded during `POST` operations (but not `$service` or `$batch` which also use the `POST` method). Let me know how you go with it.

**Comment by joeshmoe301** [comment]
Thanks.  I won't be able to try this till next week.

**Comment by RyanFarley** [comment]
That's awesome @NathanBaulch. Thanks, I'll give it a try today

**Comment by joeshmoe301** [comment]
Sorry, I just now got around to testing the changes.  Worked fine.  Thank you.
